-- use this file to map the AP location ids to your locations
-- first value is the code of the target location/item and the second is the item type override (feel free to expand the table with any other values you might need (i.e. special initial values, increments, etc.)!)
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
LOCATION_MAPPING = {
	-- Shipwreck Creek Pagies
	[625490501] = {"@Shipwreck Creek/Help Blastro/Help Blastro Pagie"},
	[625490503] = {"@Shipwreck Creek/The Wrecked Crow's Nest/The Wrecked Crow's Nest Pagie"},

	-- Hivory Towers Pagies
	[625490502] = {"@Hivory Tower/Hivory Tower Hub Entrance/Extinguish the Fire/Extinguish the Fire Pagie"},
	[625490504] = {"@Hivory Tower/Hivory Tower Hub Entrance/Entrance to Tribalstack Tropics Tome/Entrance to Tribalstack Tropics Tome Pagie"},
	[625490505] = {"@Hivory Tower/Hivory Tower Hub Entrance/Capital B Statue/On Top of Capital B Statue Pagie"},
	[625490506] = {"@Hivory Tower/Hivory Tower Hub Entrance/Fiery Pipe/Fiery Pipe"},
	[625490507] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Catch the Pagie/Catch the Pagie"},
	[625490508] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/In the Arcade Machine/In the Arcade Machine Pagie"},
	[625490509] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Slippery Slope/Slippery Slope Pagie"},
	[625490510] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Pipe Climb/Pipe Climb Pagie"},
	[625490511] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Behind the Steel Bars/Pagie behind the Steel Bars"},
	[625490512] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Underwater Challenge/Underwater Challenge Pagie"},
	[625490513] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/In the Pipes/In the Pipes Pagie"},
	[625490514] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Archive/Glass Maze Pagie"},
	[625490515] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Hivory Tower Outside (NoFlight)/Domino Books/Domino Books Pagie"},
	[625490516] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Hivory Tower Outside (NoFlight)/Hivory Towers Outside Flight/Balloon Challenge/Balloon Challenge Pagie"},
	[625490517] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Hivory Tower Outside (NoFlight)/Hivory Towers Outside Flight/Slide Challenge/Slide Challenge Pagie"},
	[625490518] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Hivory Tower Outside (NoFlight)/Hivory Towers Outside Flight/Across the Wind Turbines/Across the Wind Turbines Pagie"},
	[625490519] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Hivory Tower Outside (NoFlight)/Through the Toxic Tunnel/Through the Toxic Tunnel Pagie"},
	[625490520] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Hivory Tower Outside (NoFlight)/Novel Puzzle/Novel Puzzle Pagie"},

	-- Tribalstack Tropics Pagies
	[625490530] = {"@Tribalstack Tropics/Collectables/Tribalstack Ghost Writers Pagie"},
	[625490531] = {"@Tribalstack Tropics/Collectables/Tribalstack Quills Pagie"},
	[625490536] = {"@Tribalstack Tropics/Duke's Temple/Assist Planker Pagie"},
	[625490537] = {"@Tribalstack Tropics/Rextro's Arcade/Rextro's Arcade (Kartos Carts)"},
	[625490538] = {"@Tribalstack Tropics/Rextro's Arcade/Rextro's Hi-Score (Kartos Carts)"},
	[625490539] = {"@Tribalstack Tropics/Expanded Tropics/Tribalstack Tropics Kartos Challenge/Tribalstack Tropics Kartos Challenge Pagie"},
	[625490540] = {"@Tribalstack Tropics/Expanded Tropics/Rampo/Rampo Pagie"},
	[625490541] = {"@Tribalstack Tropics/Pollinate Plant Bulbs/Pollinate Plant Bulbs Pagie"},
	[625490542] = {"@Tribalstack Tropics/Solve the Tribalstack Tile Puzzle/Solve the Tribalstack Tile Puzzle Pagie"},
	[625490543] = {"@Tribalstack Tropics/Expanded Tropics/Assist Blastooie/Assist Blastooie Pagie"},
	[625490544] = {"@Tribalstack Tropics/Locate the Knights/Locate the Knights of Hamalot in Tribalstack Pagie"},
	[625490545] = {"@Tribalstack Tropics/Rescue Clara Lost in Tribalstack/Rescue Clara Lost in Tribalstack Pagie"},
	[625490546] = {"@Tribalstack Tropics/Expanded Tropics/Find Shovel Knight's Ruby/Find Shovel Knight's Ruby Pagie"},
	[625490547] = {"@Tribalstack Tropics/Nimble Race/Nimble Dry Canal Race Pagie"},
	[625490548] = {"@Tribalstack Tropics/Nimble Race/Nimble Frozen Canal Race Pagie"},
	[625490549] = {"@Tribalstack Tropics/Tribalstack Roll Hoop Challenge/Tribalstack Roll Hoop Challenge Pagie"},
	[625490550] = {"@Tribalstack Tropics/Expanded Tropics/Repair the Broken Bridge/Repair the Broken Bridge Pagie"},
	[625490551] = {"@Tribalstack Tropics/Assemble the Tribalstack Pagie Pieces/Assemble the Tribalstack Pagie Pieces"},
	[625490552] = {"@Tribalstack Tropics/Activate the Floating Platforms/Activate the Floating Platforms Pagie"},
	[625490553] = {"@Tribalstack Tropics/Duke's Temple/Duke's Temple Shootout Pagie"},
	[625490554] = {"@Tribalstack Tropics/Expanded Tropics/Backside of the Monument/Spew Water on Mr. Blowy Pagie"},
	[625490555] = {"@Tribalstack Tropics/Expanded Tropics/Tribalstack Glide Hoop Challenge/Tribalstack Glide Hoop Challenge Pagie"},
	[625490556] = {"@Tribalstack Tropics/Expanded Tropics/Tribalstack Tropics Kartos Challenge/The Windy Challenge Pagie"},
	[625490557] = {"@Tribalstack Tropics/Expanded Tropics/Inside the Tribalstack Monument/Inside the Tribalstack Monument Pagie"},
	[625490558] = {"@Tribalstack Tropics/Collect the Underwater Pagie/Collect the Underwater Pagie"},

	-- Glitterglace Glacier Pagies
	[625490560] = {"@Glitterglaze Glacier/Collectables/Glitterglaze Ghostwriter Pagie"},
	[625490561] = {"@Glitterglaze Glacier/Collectables/Glitterglaze Quills Pagie"},	
	[625490562] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Rextro's Arcade (Rextro's Glaciators) Pagie"},	
	[625490563] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Rextro's Hi-Score (Rextro's Glaciators) Pagie"},
	[625490565] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Icymetric Palace - Frozen Pagie"},	
	[625490566] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Icymetric Palace - Brreeeze Blok Pagie"},	
	[625490569] = {"@Glitterglaze Glacier/Glitterglaze Kartos Challenge/Glitterglaze Kartos Challenge Pagie"},
	[625490570] = {"@Glitterglaze Glacier/Frozen Path Torches/Frozen Path Torches Pagie"},
	[625490571] = {"@Glitterglaze Glacier/Pentagonal Peak/Pentagonal Peak Pagie"},
	[625490572] = {"@Glitterglaze Glacier/Find the Snowmen's Clothing/Find the Snowmen's Clothing Pagie"},
	[625490573] = {"@Glitterglaze Glacier/Glitterglaze Glide Hoop Challenge/Glitterglaze Glide Hoop Challenge Pagie"},
	[625490574] = {"@Glitterglaze Glacier/Crystalline Cave Ice Puzzle/Crystalline Cave Ice Puzzle Pagie"},
	[625490575] = {"@Glitterglaze Glacier/Sculpt the Capital B Ice Sculpture/Sculpt the Capital B Ice Sculpture Pagie"},
	[625490576] = {"@Glitterglaze Glacier/Glitterglaze Flying Hoop Challenge/Glitterglaze Flying Hoop Challenge Pagie"},
	[625490577] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Icymetric Palace - Pipes Pagie"},	
	[625490578] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Icymetric Palace - Dark Room Quiz Pagie"},	
	[625490579] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Lower/Icymetric Palace - Sonar Shot the Statues Pagie"},
	[625490581] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Icymetric Palace - Camo Cloak Pagie"},	
	[625490582] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Icymetric Palace - Burnie's Room Pagie"},	
	[625490583] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Icymetric Palace - Spike Wall Pagie"},	
	[625490584] = {"@Glitterglaze Glacier/Traverse through Gloomy Gem Grotto/Traverse through Gloomy Gem Grotto Pagie"},
	[625490585] = {"@Glitterglaze Glacier/Jump over Dice Symbols Platform/Jump over Dice Symbols Platform Pagie"},	
	[625490586] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Lower/Assist Tubbz Pagie"},	
	[625490587] = {"@Glitterglaze Glacier/Rescue Potty Mouth/Rescue Potty Mouth Pagie"},	
	[625490588] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Icymetric Palace - Acid Path Pagie"},	

	-- Moodymaze Marsh Pagies
	[625490590] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Collectables/Moodymaze Ghosts Pagie"},	
	[625490591] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Collectables/Moodymaze Quills Pagie"},	
	[625490595] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Swampy Station/Swampy Station Pagie"},	
	[625490597] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Rextro's Arcade/Rextro's Arcade (Bee Bop)"},	
	[625490598] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Rextro's Arcade/Rextro's Hi-score (Bee Bop)"},	
	[625490600] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Moodymaze Kartos Challenge/Moodymaze Kartos Challenge Pagie"},	
	[625490601] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Dusky Duct/Rescue Dolly the Trolley Pagie"},	
	[625490602] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Defeat Trev the Tenteyecle/Defeat Trev the Tenteyecle Pagie"},	
	[625490603] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Complete Ollie the Trolly's Maze/Complete Ollie the Trolly's Maze Pagie"},	
	[625490604] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Moodymaze Timed Platform Challenge/Moodymaze Timed Platform Challenge Pagie"},	
	[625490605] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Plumping Plant/Plumping Plant Puzzle Pagie"},	
	[625490606] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Moodymaze Trapped Pagie/Moodymaze Trapped Pagie"},	
	[625490607] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Cage Match/Cage Match Pagie"},	
	[625490608] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Underwater Pagie/Underwater Pagie"},	
	[625490609] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Barbed Vines/Barbed Vines Pagie"},	
	[625490610] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Murky Passage/Travel through the Murky Passage Pagie"},	
	[625490611] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Hotswitch Hollow/Hotswitch Hollow Pagie"},
	[625490612] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Scale the Tree/Scale the Tree Pagie"},	
	[625490613] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Complete Jolly's Switch Mission/Complete Jolly's Switch Mission Pagie"},	
	[625490614] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Fire Platform Challenge/Fire Platform Challenge Pagie"},
	[625490615] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Moodymaze Hoop Challenge/Moodymaze Hoop Challenge Pagie"},
	[625490616] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Get Clara's Gem/Get Clara's Gem Pagie"},
	[625490617] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Collect Panlker's Seeds/Collect Panlker's Seeds Pagie"},
	[625490618] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Remove Fungus from Wally's Garden/Remove Fungus from Wally's Garden Pagie"},	
	[625490619] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Moodymaze Hanging Pagie/Moodymaze Hanging Pagie"},

	-- Captial Cashino Pagies
	[625490620] = {"@Capital Cashino/Cashino Entry/Expanded Cashino/Collectables/Cashino Ghosts Pagie"},
	[625490621] = {"@Capital Cashino/Cashino Entry/Expanded Cashino/Collectables/Cashino Quills Pagie"},	
	[625490622] = {"@Cashino Token Pagies/Tokens 1"},	
	[625490623] = {"@Cashino Token Pagies/Tokens 2"},	
	[625490624] = {"@Cashino Token Pagies/Tokens 3"},	
	[625490625] = {"@Cashino Token Pagies/Tokens 4"},	
	[625490626] = {"@Cashino Token Pagies/Tokens 5"},	
	[625490631] = {"@Cashino Token Pagies/Tokens 6"},	
	[625490632] = {"@Cashino Token Pagies/Tokens 7"},	
	[625490633] = {"@Cashino Token Pagies/Tokens 8"},	
	[625490634] = {"@Cashino Token Pagies/Tokens 9"},	
	[625490635] = {"@Cashino Token Pagies/Tokens 10"},	
	[625490636] = {"@Cashino Token Pagies/Tokens 11"},	
	[625490637] = {"@Cashino Token Pagies/Tokens 12"},	
	[625490638] = {"@Cashino Token Pagies/Tokens 13"},	
	[625490639] = {"@Cashino Token Pagies/Tokens 14"},	
	[625490642] = {"@Cashino Token Pagies/Tokens 15"},	
	[625490643] = {"@Cashino Token Pagies/Tokens 16"},	
	[625490644] = {"@Cashino Token Pagies/Tokens 17"},	
	[625490645] = {"@Cashino Token Pagies/Tokens 18"},	
	[625490646] = {"@Cashino Token Pagies/Tokens 19"},	
	[625490627] = {"@Capital Cashino/Cashino Entry/Cashino Rextro's Arcade/Rextro's Hi-Score (Hurdle Hijinx) Pagie"},	
	[625490628] = {"@Capital Cashino/Cashino Entry/Cashino Rextro's Arcade/Rextro's Arcade (Hurdle Hijinx) Pagie"},	
	[625490629] = {"@Capital Cashino/Cashino Entry/Cashino Kartos/Cashino Kartos Challenge Pagie"},	
	[625490630] = {"@Capital Cashino/Cashino Entry/Cashino Kartos/I.N.E.P.T Boss Battle Pagie"},

	-- Galleon Galaxy Pagies
	[625490650] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Collectables/Galaxy Ghosts Pagie"},	
	[625490651] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Collectables/Galaxy Quills Pagie"},	
	[625490662] = {"@Galleon Galaxy/Galleon Entry/The Lighthouse/The Lighthouse Pagie"},	
	[625490664] = {"@Galleon Galaxy/Galleon Entry/Lunar Lockup/Lunar Lockup Pagie"},
	[625490667] = {"@Galleon Galaxy/Galleon Entry/Cosmic Cavern/Cosmic Cavern Laser Challenge Pagie"},
	[625490657] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Rextro's Arcade/Rextro's Arcade (UpNova) Pagie"},	
	[625490658] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Rextro's Arcade/Rextro's Hi-Score (UpNova) Pagie"},	
	[625490659] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Galaxy Kartos Challenge/Galaxy Kartos Challenge Pagie"},	
	[625490660] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Defeat Planette/Defeat Planette Pagie"},	
	[625490661] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/The Space Rig/The Space Rig Pagie"},	
	[625490663] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Pressure Dome/Pressure Dome Swimming Challenge Pagie"},	
	[625490665] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Complete Schell's Mission/Complete Schell's Mission Pagie"},	
	[625490666] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Space Plumbing/Space Plumbing Pagie"},	
	[625490668] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Velocity Terminal/Velocity Terminal Pagie"},	
	[625490669] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Spacecog Station/Spacecog Station Pagie"},	
	[625490670] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Black Hole in One/Black Hole in One Pagie"},	
	[625490671] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Turn on the Captain's Lamp/Turn on the Captain's Lamp Pagie"},	
	[625490672] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Pressure Dome/Pressure Dome Security Gauntlet Pagie"},	
	[625490673] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Melt Rusto's Ice Cube/Melt Rusto's Ice Cube Pagie"},	
	[625490674] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Test of Strength Switch/Test of Strength Switch Pagie"},	
	[625490675] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Galaxy Knights Key/Galaxy Knights Key Pagie"},	
	[625490676] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Star Fishing/Star Fishing Minigame Pagie"},	
	[625490677] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Galaxy Pagie Piece/Galaxy Pagie Piece"},	
	[625490678] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Energy Ball Switch/Energy Ball Switch Pagie"},	
	[625490679] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Galaxy Nimble Race/Galaxy Nimble Race Pagie"},	

	-- Abilities
	[625491500] = {"@Shipwreck Creek/Trowzer's Shop/Trowzer's Tail Twirl"},
	[625491501] = {"@Hivory Tower/Hivory Tower Hub Entrance/Trowzer's Shop/Trowzer's Reptile Roll"},
	[625491502] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Trowzer's Shop/Trowzer's Glide"},
	[625491503] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Archive/Trowzer's Buddy Bubble"},
	[625491504] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Trowzer's Shop/Trowzer's Camo Cloak"},
	[625491505] = {"@Hivory Tower/Hivory Tower Hub Entrance/Hivory Towers Hub B/Hivory Tower Waterworks/Hivory Tower Outside (NoFlight)/Trowzer's Shop/Trowzer's Flappy Flight"},
	[625491510] = {"@Tribalstack Tropics/Duke's Temple/Trowzer's Sonar Shot"},
	[625491511] = {"@Tribalstack Tropics/Duke's Temple/Trowzer's Slurp Shot"},
	[625491512] = {"@Tribalstack Tropics/Duke's Temple/Trowzer's Buddy Slam"},
	[625491513] = {"@Glitterglaze Glacier/Trowzer's Shop/Trowzer's Slurp State"},
	[625491514] = {"@Glitterglaze Glacier/Trowzer's Shop/Trowzer's Lizard Leap"},
	[625491515] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Trowzer's Shop/Trowzer's Lizard Lash"},
	[625491516] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Trowzer's Shop/Trowzer's Sonar 'Splosion"},
	[625491517] = {"@Capital Cashino/Cashino Entry/Trowzer's Shop/Trowzer's Reptile Rush"},
	[625491518] = {"@Galleon Galaxy/Galleon Entry/Trowzer's Shop/Trowzer's Sonar Shield"},

	--Mollycools
	[625491020] = {"@Tribalstack Tropics/Tropics Mollycool/Tropics Mollycool"},
	[625491021] = {"@Glitterglaze Glacier/Glacier Mollycool/Glacier Mollycool"},
	[625491022] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Marsh Mollycool/Marsh Mollycool"},
	[625491023] = {"@Capital Cashino/Cashino Entry/Cashino Mollycool/Cashino Mollycool"},
	[625491024] = {"@Galleon Galaxy/Galleon Entry/The Lighthouse/Galaxy Mollycool"},

	-- Play Coins
	[625491030] = {"@Tribalstack Tropics/Tropics Play Coin/Tropics Play Coin"},
	[625491031] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Glacier Play Coin"},
	[625491032] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Marsh Play Coin/Marsh Play Coin"},
	[625491033] = {"@Capital Cashino/Cashino Entry/Cashino Play Coin/Cashino Play Coin"},
	[625491034] = {"@Galleon Galaxy/Galleon Entry/Galaxy Play Coin/Galaxy Play Coin"},

	-- Health Booster
	[625491000] = {"@Shipwreck Creek/Health Booster/Shipwreck Creek Health Booster"},
	[625491001] = {"@Tribalstack Tropics/Expanded Tropics/Backside of the Monument/Tropics Health Booster"},
	[625491002] = {"@Glitterglaze Glacier/Expanded Glacier/Icymetric Palace Upper/Glacier Health Booster"},
	[625491003] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Marsh Health Booster/Marsh Health Booster"},
	[625491004] = {"@Capital Cashino/Cashino Entry/Cashino Health Booster/Cashino Health Booster"},
	[625491005] = {"@Galleon Galaxy/Galleon Entry/Expanded Galaxy/Pressure Dome/Galaxy Health Booster"},

	-- Energy Booster
	[625491010] = {"@Hivory Tower/Hivory Tower Hub Entrance/Capital B Statue/Hivory Towers Energy Booster"},
	[625491011] = {"@Tribalstack Tropics/Expanded Tropics/Tribalstack Energy Booster/Tribalstack Energy Booster"},
	[625491012] = {"@Glitterglaze Glacier/Glacier Energy Booster/Glacier Energy Booster"},	
	[625491013] = {"@Moodymaze Marsh/Moodymaze Marsh Entry/Expanded Marsh/Marsh Energy Booster/Marsh Energy Booster"},
	[625491014] = {"@Capital Cashino/Cashino Entry/Cashino Energy Booster/Cashino Energy Booster"},
	[625491015] = {"@Galleon Galaxy/Galleon Entry/Cosmic Cavern/Galaxy Energy Booster"},
}